before_script:
  - mvn clean -B

build_jdk7:
  image: maven:3-jdk-7
  only:
    - master
    - testing
  script:
    - mvn install -B -DskipTests -Dgpg.skip

build_jdk8:
  image: maven:3-jdk-8
  only:
    - master
    - testing
  script:
    - mvn install -B -DskipTests -Dgpg.skip

