openjdk6:
  only:
    - master
    - testing
  script:
    - OPENJDK6=$(update-alternatives --list java | grep 'java-6-openjdk-amd64' | sed 's/\/bin\/java$/''/g')
    - export JAVA_HOME=$OPENJDK6:$JAVA_HOME
    - java -version
    - mvn --version
    - mvn clean -B
    - mvn install -B -DskipTests -Dgpg.skip

openjdk7:
  only:
    - master
    - testing
  script:
    - OPENJDK7=$(update-alternatives --list java | grep 'java-7-openjdk-amd64' | sed 's/\/bin\/java$/''/g')
    - export JAVA_HOME=$OPENJDK7:$JAVA_HOME
    - java -version
    - mvn --version
    - mvn clean -B
    - mvn install -B -DskipTests -Dgpg.skip

oraclejdk8:
  only:
    - master
    - testing
  script:
    - ORACLEJDK8=$(update-alternatives --list java | grep 'java-8-oracle' | sed 's/\/bin\/java$/''/g')
    - export JAVA_HOME=$ORACLEJDK8:$JAVA_HOME
    - java -version
    - mvn --version
    - mvn clean -B
    - mvn install -B -DskipTests -Dgpg.skip
