# environment settings
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: QerhFAEkdOlJ5AbVjaIDyXKW1SF0UE0ytcY0WsSGRWVjvl60VK7L1BqIIfFOh4nrPHAnvNTOI/AKozORvoaw3gr4XLCxWSRVwkxEkXX6cC6o/EW64vVDtvUoEHsvMGndGUw0VUIzqo7Mte4hY1kWKDm2Ny9vTrShQKnWNsJ6+NGVX+2upJsM+UffqLxcm71awRnJOicnwTZ3JgAae/pLQZp66vqW5/7fGzBY3E9GYQoIn2WLNYVry2iRc6hetJky++kToN72W8FAYSJUi6k+S7K6YnejOD64si0KSFEmr9RtpnGrhOK0m8mf0qwpHMRO5vPiYo1sXL3dKkvF+PuZR0qoFXaBJd9Txi5PwDRZStxbcIH/3tRweSjGug8uXEyjnTvZmz1+RgEI2vFEtBfkLqz8qf6QjBHoO97dbbiUT6N/m1Jfug+MGlDqJ1rgEvXelkOOUa/SgDn7kiptt1gs+KTXmE6VO2oiqfhLw1gvXaHevjmpVlFN0kRkz0pcc3ud+lbD3730c0n05NPirp2JiN1fBmvzFm8gKexPgJYmHSDla1DHDiyQri6SB9GjQIqCZoE2LXNjL+ln+4CJ2W2IHfALBtbWg3R1zE2MMxcwKUY0RJMip1P78t0SMm8xdFJXcFj8k0Bl1+jXV5iMyTOifvX58ilTVhqoSh6nNUcjJ7E=
    # Coverity run condition (avoid matrix multiple runs), need customized
    # build script. Need an update if new matrix cases.
    - coverity_scan_run_condition='"$JDK" = openjdk7'

# project language
language:
  java

# branches to build (whitelist)
branches:
  only:
    - master
    - testing

# java versions
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

# install command
install:
  mvn install -DskipTests -Dgpg.skip 

# success and failure notifications
notifications:
  email:
    recipients:
      - maxnitze@cs.uni-bremen.de
    on_success: change
    on_failure: always

# addons
addons:
  coverity_scan:
    project:
      name: "razr69/fomeja"
    notification_email: maxnitze@cs.uni-bremen.de
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true compile"
    branch_pattern: testing

after_success:
  - mvn clean verify jacoco:report coveralls:report -Dgpg.skip
